### ISSUE TITLE
Port project to RPi

### ISSUE THREAD

**Issue by jtnoboru** [jtnoboru/491Aproj#16]

**Comment by jtnoboru** [comment]
Tasks completed:
- Loaded project onto RPi
- Updated RPi OS (Raspbian Jessie)
- Installed OpenCV from source
- Various image formats from disk
- Video  I/O packages
- GTK (Open CV GUI)

**Comment by sbthegreat** [comment]
http://pklab.net/?id=392&lang=EN
section: "Formatting your USB memory as Linux Partition"
I think this explains how to DL opencv onto external memory?

**Comment by jtnoboru** [comment]
Continued task onto W7
