### ISSUE TITLE
Refining motion tracking

### ISSUE THREAD

**Issue by jtnoboru** [jtnoboru/491Aproj#2]

**Comment by jtnoboru** [comment]
http://www.pyimagesearch.com/2015/05/25/basic-motion-detection-and-tracking-with-python-and-opencv/

**Comment by jtnoboru** [comment]
Researched, however, we determined that it would be best to keep our HSV tracking.

**Comment by sbthegreat** [comment]
Trying out new method of tracking, can view on mainController in my fork of the repository
